# server port
server:
  port: 0

---
# logging
logging:
  level:
    org.hibernate: debug
    com.everyschool.boardservice: debug

---
# MSA setting
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://every-school.com:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

#spring default setting
spring:
  application:
    name: board-service
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_batch_fetch_size: 100
    open-in-view: true

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, info, metrics, prometheus, busrefresh

cloud:
  aws:
    s3:
      bucket: everyschool
    stack.auto: false
    region.static: ap-northeast-2
    credentials:
      accessKey: ${my.accessKey}
      secretKey: ${my.secretKey}