server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}}

spring:
  application:
    name: apigateway-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  cloud:
    gateway:
      routes:
        # USER SERVICE
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/login
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/join
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/auth/**
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/actuator/**
            - Method=GET,POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/v1/index
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/v1/code-groups/**
            - Method=GET, POST, DELETE
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/v1/**
            - Method=GET, POST, PATCH, DELETE
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter
        # school-service
        - id: school-service
          uri: lb://SCHOOL-SERVICE
          predicates:
            - Path=/school-service/api/**
        # board-service
        - id: board-service
          uri: lb://BOARD-SERVICE
          predicates:
            - Path=/board-service/v1/**
            - Method=GET, POST, PATCH, DELETE
        - id: board-service
          uri: lb://BOARD-SERVICE
          predicates:
            - Path=/board-service/actuator/**
            - Method=GET,POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/board-service/(?<segment>.*), /$\{segment}
        # chat-service
        - id: chat-service
          uri: lb://CHAT-SERVICE
          predicates:
            - Path=/chat-service/v1/**
            - Method=GET, POST, PATCH, DELETE
        - id: chat-service
          uri: lb://CHAT-SERVICE
          predicates:
            - Path=/chat-service/actuator/**
            - Method=GET,POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/chat-service/(?<segment>.*), /$\{segment}
        # consult-service
        - id: consult-service
          uri: lb://CONSULT-SERVICE
          predicates:
            - Path=/consult-service/v1/**
            - Method=GET, POST, PATCH, DELETE
        - id: consult-service
          uri: lb://CONSULT-SERVICE
          predicates:
            - Path=/consult-service/actuator/**
            - Method=GET,POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/consult-service/(?<segment>.*), /$\{segment}



management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, httptrace, info, metrics, prometheus, busrefresh

