server:
  port: 0

# logging
logging:
  level:
    org.hibernate: debug
    com.everyschool.schoolservice: debug

spring:
  application:
    name: school-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  # h2 setting
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console

  # jpa setting
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true
    open-in-view: true

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, info, metrics, prometheus, busrefresh


